defaults:
  - base

_target_: gflownet.envs.amp.AMP

id: aptamers
func: nupack energy
# Minimum and maximum length for the sequences
min_seq_length: 30
max_seq_length: 30
# Number of letters in alphabet
n_alphabet: 20
# Minimum and maximum number of steps in the action space
min_word_len: 1
max_word_len: 1
# Buffer
buffer:
  replay_capacity: 10
  train:
    path: null
    n: 20
    seed: 168
    output: None
# TODO: Might need to delete irrelevant params after updating buffer
  test:
    base: None
    path: null
    n: 10
    seed: 168
    output: None