defaults:
  - base

_target_: gflownet.envs.choices.Choices

id: options
# String representations of the options
# If None, indices starting from 1 are used.
options: null
# Number of options (ignored if a list of options is passed)
n_options: 3
max_selection: 2
can_select_fewer_than_max: False
with_replacement: True
source_readable: "<source>"
