defaults:
  - base

_target_: gflownet.envs.grid.Grid

id: grid
# Dimensions of hypergrid
n_dim: 2
# Number of cells per dimension
length: 3
# Maximum increment per each dimension that can be done by one action
max_increment: 1
# Maximum number of dimensions that can be incremented by one action
max_dim_per_action: 1
# Mapping coordinates
cell_min: -1
cell_max: 1
# Buffer
buffer:
  data_path: null
  train: null
  test:
    type: all
