defaults:
  - base

_target_: src.gflownet.envs.grid.Grid

id: grid
func: corners
# Dimensions of hypergrid
n_dim: 2
# Number of cells per dimension
length: 3
# Minimum and maximum number of steps in the action space
min_step_len: 1
max_step_len: 1
# Mapping coordinates
cell_min: -1
cell_max: 1
# Buffer
buffer:
  data_path: null
  train:
    path: null
    seed: 167
    n: null
    output: null
  test:
    all: True
    path: null
    seed: 167
    n: null
    output: null
