defaults:
  - base

_target_: gflownet.envs.tree.Tree

id: tree
# Data set
data_path: ${user.data.root}/toy1.csv
# Max depth
max_depth: 2
# Continuous
continuous: True
# Number of threshold values for discrete case (ignored if continuous)
n_thresholds: 9
# Policy format
policy_format: mlp
# Test arguments
test_args:
  top_n_trees: 0

# Policy parameters
threshold_components: 3
beta_params_min: 0.1
beta_params_max: 100.0
fixed_distr_params:
  beta_alpha: 2.0
  beta_beta: 5.0
random_distr_params:
  beta_alpha: 1.0
  beta_beta: 1.0
# Buffer
buffer:
  data_path: null
  train: null
  test:
    type: random
    n: 1000
