_target_: gflownet.utils.logger.Logger

do:
  online: True
  times: False

project_name: "GFlowNet"

# Train metrics
train:
  period: 1
# Test metrics
test:
  first_it: False
  period: 100
  n: 1000
  kde:
    bandwidth: 0.1
    kernel: gaussian
  n_top_k: 5000
  top_k: 100
  top_k_period: -1
  # Number of backward trajectories to estimate the log likelihood of each test data point
  n_trajs_logprobs: 10
  # Maximum number of test data points to compute log likelihood probs.
  max_data_logprobs: 1e5
# Oracle metrics
oracle:
  period: 100000
  k:
    - 1
    - 10
    - 100
# Policy model checkpoints
checkpoints:
  period: 1000

# Log dir
logdir:
  root: ./logs
  ckpts: ckpts
  overwrite: True
debug: False
lightweight: False
progress: True
context: "0"
