defaults:
  - base

_target_: gflownet.utils.logger.Logger

do:
  online: True
  times: True

project_name: "scratch"
tags: 
    - dummy1
    - dummy2
sampler:
  policy:
    # Period (number of iterations) of saving models
    period: 1000
  train:
    # Period (number of iterations) of computing test metrics
    period: 1
  test:
    # Period (number of iterations) of computing test metrics
    period: 1000
  oracle:
    # Period (number of iterations) for computing oracle metrics
    period: 1000
    # List of K, for Top-K oracle metrics
    k:
      - 1
      - 10
      - 100
