defaults:
  - base

_target_: gflownet.utils.logger.Logger

do:
  online: True

project_name: "ActiveLearningPipeline"
tags: 
    - dummy1
    - dummy2
record_time: False
sampler:
  policy:
    # Period (number of iterations) of saving models
    period: 10
  train:
    # Period (number of iterations) of computing test metrics
    period: 1
  test:
    # Period (number of iterations) of computing test metrics
    period: 1
  oracle:
    # Period (number of iterations) for computing oracle metrics
    period: 10
    # List of K, for Top-K oracle metrics
    k:
      - 1
      - 10
      - 100
