name: Code Formatting and Tests

on: [push]

jobs:
  Continuous-Integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo code
        uses: actions/checkout@v3

      - name: Run Black on main source code
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./gflownet/"

      - name: Run Black on unit test code
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./tests/"

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install CUDA 11.7
        uses: Jimver/cuda-toolkit@v0.2.11
        id: cuda-toolkit
        with:
          cuda: '11.7.1'

      - name: Install code dependencies
        run: bash ./setup/continuous_integration.sh pip install --upgrade

      - name: Install GFlowNet repo
        run: pip install https://github.com/alexhernandezgarcia/gflownet/archive/main.zip --quiet

      - name: Install Pytest and Isort
        run: pip install pytest isort

      - name: Validate import format in main source code
        run: isort --profile black ./gflownet/ --check-only

      - name: Validate import format in unit test code
        run: isort --profile black ./tests/ --check-only

      - name: Run unit tests
        run: pytest